---
swagger: "2.0"
info:
  description: "Customer Service application for donating and requesting second-hand\
    \ books"
  version: "1.0.0"
  title: "Book Exchange API"
host: "z7xnekbzrd.execute-api.us-east-1.amazonaws.com"
basePath: "/dev"
schemes:
- "https"
paths:
  /addtolist:
    post:
      operationId: "AddtoFavouriteList"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "MODEL604ea3"
        required: true
        schema:
          $ref: "#/definitions/MODEL604ea3"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Success"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
        "500":
          description: "500 response"
          schema:
            $ref: "#/definitions/Error"
        "403":
          description: "403 response"
          schema:
            $ref: "#/definitions/Error"
    options:
      consumes:
      - "application/json"
      parameters:
      - name: "Access-Control-Allow-Headers"
        in: "header"
        required: false
        type: "string"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /donate:
    post:
      operationId: "donateBook"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "Donation"
        required: true
        schema:
          $ref: "#/definitions/Donation"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/DonationResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "500":
          description: "500 response"
          schema:
            $ref: "#/definitions/Error"
        "403":
          description: "403 response"
          schema:
            $ref: "#/definitions/Error"
    options:
      consumes:
      - "application/json"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /donate/photos/{key}:
    post:
      parameters:
      - name: "key"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
    put:
      parameters:
      - name: "key"
        in: "path"
        required: true
        type: "string"
      responses: {}
    options:
      consumes:
      - "application/json"
      parameters:
      - name: "key"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /getuserinfo:
    get:
      parameters:
      - name: "user_id"
        in: "query"
        required: true
        type: "string"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
    options:
      consumes:
      - "application/json"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /message:
    get:
      parameters:
      - name: "user_id"
        in: "query"
        required: true
        type: "string"
      responses:
        "200":
          description: "200 response"
    post:
      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "SendMessage"
        required: true
        schema:
          $ref: "#/definitions/SendMessage"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "500":
          description: "500 response"
        "403":
          description: "403 response"
    options:
      consumes:
      - "application/json"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /remove:
    post:
      operationId: "removeDonatedBook"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "MODEL659241"
        required: true
        schema:
          $ref: "#/definitions/MODEL659241"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/DonationResponse"
        "500":
          description: "500 response"
          schema:
            $ref: "#/definitions/Error"
        "403":
          description: "403 response"
          schema:
            $ref: "#/definitions/Error"
  /request:
    post:
      operationId: "requestBook"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "Request"
        required: true
        schema:
          $ref: "#/definitions/Request"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/RequestResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
        "500":
          description: "500 response"
          schema:
            $ref: "#/definitions/Error"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
        "403":
          description: "403 response"
          schema:
            $ref: "#/definitions/Error"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
    options:
      consumes:
      - "application/json"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /search:
    get:
      operationId: "searchBook"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "Search"
        required: true
        schema:
          $ref: "#/definitions/Search"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/SearchResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "500":
          description: "500 response"
          schema:
            $ref: "#/definitions/Error"
        "403":
          description: "403 response"
          schema:
            $ref: "#/definitions/Error"
    options:
      consumes:
      - "application/json"
      parameters:
      - name: "Access-Control-Allow-Headers"
        in: "header"
        required: false
        type: "string"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
definitions:
  DonationResponse:
    $ref: "#/definitions/Donation"
  Book:
    type: "object"
    properties:
      book_id:
        type: "string"
      book_name:
        type: "string"
      cover_picture:
        type: "string"
  Donation:
    type: "object"
    properties:
      donation_id:
        type: "string"
      book_id:
        type: "string"
      user:
        type: "string"
      timestamp:
        type: "string"
        format: "datetime"
      tag:
        type: "array"
        items:
          type: "string"
  Search:
    type: "object"
    properties:
      name:
        type: "string"
      tag:
        type: "string"
      category:
        type: "string"
  Request:
    type: "object"
    properties:
      donation_id:
        type: "string"
      user:
        type: "string"
      timestamp:
        type: "string"
        format: "datetime"
  Error:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
  MODEL604ea3:
    type: "object"
    properties:
      book_name:
        type: "string"
  MODEL659241:
    type: "object"
    properties:
      donation_id:
        type: "string"
  RequestResponse:
    $ref: "#/definitions/Request"
  Success:
    type: "string"
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
  SearchResponse:
    type: "object"
    properties:
      book_list:
        type: "array"
        items:
          type: "object"
          properties:
            book_information:
              $ref: "#/definitions/Book"
            donation_list:
              type: "array"
              items:
                $ref: "#/definitions/Donation"
  SendMessage:
    type: "object"
    properties:
      sender:
        type: "string"
      receipent:
        type: "string"
      content:
        type: "string"
